server.port=8083
spring.application.name=alert-service

spring.cloud.stream.bindings.alertHandler-in-0.destination=threshold-breaches
spring.cloud.stream.bindings.alertHandler-in-0.group=alert-group
spring.cloud.stream.kafka.binder.brokers=localhost:9092