eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.application.name=alert-service

spring.cloud.stream.bindings.alertHandler-in-0.destination=threshold-breaches
spring.cloud.stream.bindings.alertHandler-in-0.group=alert-group
spring.cloud.stream.kafka.binder.brokers=localhost:9092