server.port=8084
spring.application.name=telemetry-composite-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Circuit breaker stanje vidljivo preko /actuator/health
management.endpoints.web.exposure.include=health,info
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always